import streamlit as st
from google import genai
from google.genai import types
import json


API_KEY = st.secrets["GEMINI_API_KEY"]  # 👈 แทนที่ด้วยคีย์ของคุณ

if API_KEY == "YOUR_API_KEY_HERE":
    st.error("กรุณาใส่ API key ในตัวแปร API_KEY ก่อนรัน")
    st.stop()

client = genai.Client(api_key=API_KEY)

generation_config = types.GenerateContentConfig(
    response_mime_type="application/json",
)

PROMPT_TEMPLATES = {

    # ---------- Part A : Absolute extrema ----------
    "A1: Absolute Extrema": (
        "You are an AI Question Generator for a Calculus I final review.\n"
        "Original exam model:\n"
        "A1(c) จงหาค่าสูงสุดและต่ำสุดสัมบูรณ์ของฟังก์ชัน $f(x)=x^{3}-6x^{2}+9x+3$ สำหรับ $-1\le x\le5$.\n\n"
        "Your task:\n"
        "1) Generate ONE NEW absolute extrema problem that follows the same logic (find f', find critical points, test points) but is significantly harder.\n"
        "   - The function $f(x)$ must be more complex than a polynomial. Use a combination of polynomial, trigonometric, or exponential functions (e.g., $f(x) = x - 2\\sin(x)$ or $f(x) = x \\cdot e^{-x/2}$). \n"
        "   - The goal is to make the calculation 'ถึกขึ้น' (more tedious).\n"
        "   - The critical points should be non-integers (e.g., involving $\\pi$, $\\sqrt{3}$, or fractions) making the final comparison of values more difficult.\n"
        "   - The interval $[a, b]$ should be chosen appropriately for the function.\n"
        "2) Solve it completely, showing all steps: finding the derivative, solving for critical points, and evaluating $f(x)$ at all critical points and endpoints to find the absolute max/min.\n\n"
        "VERY IMPORTANT LaTeX RULES:\n"
        "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
        "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
        "- Do NOT start with words like `Let` outside math mode.\n"
        "- If you need to write words (Let, Find f'(x), Critical points, Endpoints, Compare, etc.), wrap them inside `\\\\text{...}`.\n"
        "- Example of the STYLE (example only):\n"
        "  \"\\\\begin{align*}\n"
        "     f(x) &= x - 2\\sin(x) \\\\text{ on } [0, 2\\pi] \\\\\n"
        "     f'(x) &= 1 - 2\\cos(x) \\\\\n"
        "     \\\\text{Set } f'(x) &= 0 \\\\Rightarrow 1 - 2\\cos(x) = 0 \\\\Rightarrow \\cos(x) = \\frac{1}{2} \\\\\n"
        "     \\\\text{Critical points in } [0, 2\\pi] &\\\\text{ are } x = \\frac{\\pi}{3} \\\\text{ and } x = \\frac{5\\pi}{3} \\\\\n"
        "     \\\\text{Compare values:} \\\\\n"
        "     f(0) &= 0 - 2\\sin(0) = 0 \\\\\n"
        "     f(2\\pi) &= 2\\pi - 2\\sin(2\\pi) = 2\\pi \\approx 6.28 \\\\\n"
        "     f(\\pi/3) &= \\frac{\\pi}{3} - 2\\sin(\\frac{\\pi}{3}) = \\frac{\\pi}{3} - 2(\\frac{\\sqrt{3}}{2}) = \\frac{\\pi}{3} - \\sqrt{3} \\approx 1.047 - 1.732 = -0.685 \\\\\n"
        "     f(5\\pi/3) &= \\frac{5\\pi}{3} - 2\\sin(\\frac{5\\pi}{3}) = \\frac{5\\pi}{3} - 2(-\\frac{\\sqrt{3}}{2}) = \\frac{5\\pi}{3} + \\sqrt{3} \\approx 5.236 + 1.732 = 6.968 \\\\\n"
        "     \\\\text{Abs. Min} &= \\frac{\\pi}{3} - \\sqrt{3} \\\\\n"
        "     \\\\text{Abs. Max} &= \\frac{5\\pi}{3} + \\sqrt{3}\n"
        "   \\\\end{align*}\".\n\n"
        "Output format:\n"
        "{\n"
        "  \"question_latex\": \"\\\\text{จงหาค่าสูงสุดและต่ำสุดสัมบูรณ์ของฟังก์ชัน } f(x) = ... \\\\text{ บนช่วง } [a, b]\",\n"
        "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
        "}\n"
        "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
    ),

    "A2: Optimization": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "A2. (a) จงหาพื้นที่ที่มากที่สุดที่เป็นไปได้ของสามเหลี่ยมหน้าจั่วที่แนบอยู่ในวงกลมรัศมี 1 หน่วย\n"
    "    (b) จงหาความยาวเส้นรอบรูปที่มากที่สุดที่เป็นไปได้ของสามเหลี่ยมหน้าจั่วที่แนบอยู่ในวงกลมรัศมี 1 หน่วย\n\n"
    "Your task:\n"
    "1) Generate ONE NEW optimization problem that follows the same logic (set up a function for a quantity to be maximized/minimized, find its derivative, find critical points, and test) but is significantly harder.\n"
    "   - This new problem should involve 3D geometry inscribed in 3D geometry (e.g., cone in a sphere, cylinder in a sphere, cylinder in a cone).\n"
    "   - A classic harder problem is finding the maximum volume of a cone inscribed in a sphere.\n"
    "   - Give a specific value for the radius (e.g., R=6 or R=3) to make the final answer an explicit number.\n"
    "   - The question should ask for the *dimensions* (like height and radius) of the shape, not just the max volume.\n"
    "2) Solve it completely, showing all steps: setting up the volume function $V$ in terms of one variable (like height $h$ or an internal radius $x$), finding $V'$, solving $V'=0$, and testing points to find the maximum.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Setup, Volume, Derivative, Critical points, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Let } R &\\\\text{ be the sphere radius, } R=6. \\\\\n"
    "     \\\\text{Let } r &\\\\text{ be the cone's base radius and } h \\\\text{ be its height.} \\\\\n"
    "     \\\\text{From a cross-section, we relate } r, h, \\\\text{ and } R. \\\\\n"
    "     \\\\text{Let the cone vertex be at the bottom. Height is } h. \\\\\n"
    "     \\\\text{The center of the sphere is at height } h-R \\\\text{ from the cone base.} \\\\\n"
    "     r^2 + (h-R)^2 &= R^2 \\\\\n"
    "     r^2 &= R^2 - (h^2 - 2hR + R^2) = 2hR - h^2 \\\\\n"
    "     \\\\text{Using } R=6: r^2 &= 12h - h^2 \\\\\n"
    "     \\\\text{Volume } V &= \\\\frac{1}{3} \\\\pi r^2 h = \\\\frac{1}{3} \\\\pi (12h - h^2) h \\\\\n"
    "     V(h) &= \\\\frac{\\\\pi}{3} (12h^2 - h^3) \\\\text{, for } 0 \\\\le h \\\\le 12 \\\\\n"
    "     V'(h) &= \\\\frac{\\\\pi}{3} (24h - 3h^2) = \\\\pi h(8 - h) \\\\\n"
    "     \\\\text{Set } V'(h) &= 0 \\\\Rightarrow h=0 \\\\text{ (min volume) or } h=8. \\\\\n"
    "     \\\\text{Max volume occurs at } h=8. \\\\\n"
    "     \\\\text{At } h=8, r^2 &= 12(8) - 8^2 = 96 - 64 = 32 \\\\\n"
    "     r &= \\\\sqrt{32} = 4\\\\sqrt{2} \\\\\n"
    "     \\\\text{Dimensions:} &\\\\text{ height } h=8, \\\\text{ radius } r=4\\\\sqrt{2}. \\\\\n"
    "     \\\\text{Max Volume } V &= \\\\frac{1}{3} \\\\pi (32)(8) = \\\\frac{256\\\\pi}{3}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาขนาด (ความสูง } h \\\\text{ และรัศมีฐาน } r)\\\\text{ ของกรวยกลมตรงที่มีปริมาตรมากที่สุด ... R=...}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
    ),
    
    "A3: Limits": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "A3(g) $lim_{x\\rightarrow 0^{+}}(\\frac{e^{x}}{ln(1+x)}-\\frac{1}{x})$\n"
    "A3(i) $lim_{x\\rightarrow 0^{+}}(\\frac{1}{x}-csc~x)$\n"
    "A3(j) $lim_{x\\rightarrow -\\infty}x~ln(\\frac{3x-1}{3x+1})$\n\n"
    "Your task:\n"
    "1) Generate ONE NEW limit problem that follows the most complex logic from A3: indeterminate forms $0 \\cdot \\infty$ or $\\infty - \\infty$.\n"
    "   - The problem MUST require significant algebraic manipulation (e.g., combining fractions, or rewriting as a single fraction) *before* L'Hopital's rule can be applied.\n"
    "   - The goal is to be 'ถึกขึ้น' (more tedious): After the initial manipulation, the resulting $0/0$ form should require L'Hopital's rule to be applied at least **twice** or **three times** to solve.\n"
    "   - Do not create a simple $0/0$ or $\\infty/\\infty$ problem.\n"
    "2) Solve it completely, showing all steps: the initial form, the algebraic manipulation, and all subsequent applications of L'Hopital's rule.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Form, Combine, L'H, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only for A3(i)):\n"
    "  \"\\\\begin{align*}\n"
    "     L &= \\\\lim_{x\\\\to 0^{+}}(\\\\frac{1}{x}-c s c~x) \\\\quad (\\\\text{Form } \\\\infty - \\\\infty) \\\\\n"
    "       &= \\\\lim_{x\\\\to 0^{+}}(\\\\frac{1}{x} - \\\\frac{1}{\\\\sin x}) \\\\\n"
    "       &= \\\\lim_{x\\\\to 0^{+}} \\\\frac{\\\\sin x - x}{x \\\\sin x} \\\\quad (\\\\text{Form } 0/0) \\\\\n"
    "       &\\\\overset{L'H}{=} \\\\lim_{x\\\\to 0^{+}} \\\\frac{\\\\cos x - 1}{\\\\sin x + x \\\\cos x} \\\\quad (\\\\text{Form } 0/0) \\\\\n"
    "       &\\\\overset{L'H}{=} \\\\lim_{x\\\\to 0^{+}} \\\\frac{-\\\\sin x}{\\\\cos x + \\\\cos x - x \\\\sin x} \\\\\n"
    "       &= \\\\frac{-0}{1 + 1 - 0} = 0\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาค่าลิมิต } \\\\lim_{x\\\\to ...} ...\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
    ),
    
    "B1: Indeterminate Powers": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "B1(a) จงหาค่าลิมิต $lim_{x\\rightarrow 0}((1-sin~2x)^{1/x}+(1-cos~3x)^{sin~x})$\n"
    "B1(c) จงหาค่าลิมิต $lim_{x\\rightarrow \\infty}(2x+3)^{1/ln(3x+2)}\\cdot(\\pi-2~arctan~x)^{\\pi/x}$\n\n"
    "Your task:\n"
    "1) Generate ONE NEW limit problem that follows the core logic of B1: it must be a SUM or PRODUCT of **two separate indeterminate power limits** (e.g., $1^\\infty$, $0^0$, $\\infty^0$).\n"
    "   - The user must be forced to solve two independent limits (L1 and L2) and then add or multiply the results.\n"
    "   - The goal is to be 'ถึกขึ้น' (more tedious): The calculation for at least one of the sub-limits (after taking $\\ln y$ and setting up the $0/0$ or $\\infty/\\infty$ form) must require a complex application of L'Hopital's rule (e.g., involving product rule, chain rule, or multiple applications).\n"
    "   - Example idea: $\\lim_{x\\to 0^+} (\\frac{1}{x})^{\\tan x} + (e^x + \\sin x)^{1/x}$\n"
    "2) Solve it completely, showing all steps: identify the two sub-limits (L1, L2), solve each one using the $\\ln y$ and L'Hopital's rule method, then combine them for the final answer.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Part 1, Part 2, Final Answer, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Let } L &= \\\\lim_{x\\\\to 0^+} ( (x)^{\\\\sin x} + (1+3x)^{1/x} ) \\\\\n"
    "     \\\\text{Let } L_1 &= \\\\lim_{x\\\\to 0^+} (x)^{\\\\sin x} \\\\quad (\\\\text{Form } 0^0) \\\\\n"
    "     \\\\text{Let } y_1 &= x^{\\\\sin x} \\\\Rightarrow \\\\ln y_1 = \\\\sin x \\\\ln x = \\\\frac{\\\\ln x}{\\\\csc x} \\\\quad (\\\\text{Form } \\\\infty/\\\\infty) \\\\\n"
    "     \\\\lim_{x\\\\to 0^+} \\\\ln y_1 &\\\\overset{L'H}{=} \\\\lim_{x\\\\to 0^+} \\\\frac{1/x}{-\\\\csc x \\\\cot x} = \\\\lim_{x\\\\to 0^+} \\\\frac{-\\\\sin^2 x}{x \\\\cos x} \\\\quad (\\\\text{Form } 0/0) \\\\\n"
    "     &\\\\overset{L'H}{=} \\\\lim_{x\\\\to 0^+} \\\\frac{-2\\\\sin x \\\\cos x}{\\\\cos x - x \\\\sin x} = \\\\frac{-0}{1 - 0} = 0 \\\\\n"
    "     \\\\text{Therefore } L_1 &= e^0 = 1. \\\\\n"
    "     \\\\text{Part 2: } L_2 &= \\\\lim_{x\\\\to 0^+} (1+3x)^{1/x} \\\\quad (\\\\text{Form } 1^\\\\infty) \\\\\n"
    "     \\\\text{Let } y_2 &= (1+3x)^{1/x} \\\\Rightarrow \\\\ln y_2 = \\\\frac{\\\\ln(1+3x)}{x} \\\\quad (\\\\text{Form } 0/0) \\\\\n"
    "     \\\\lim_{x\\\\to 0^+} \\\\ln y_2 &\\\\overset{L'H}{=} \\\\lim_{x\\\\to 0^+} \\\\frac{3/(1+3x)}{1} = 3 \\\\\n"
    "     \\\\text{Therefore } L_2 &= e^3. \\\\\n"
    "     \\\\text{Final Answer: } L &= L_1 + L_2 = 1 + e^3\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาค่าลิมิต } \\\\lim_{x\\\\to ...} ...\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
    ),
    "B2: Curve Sketching": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "B2. จงวิเคราะห์และร่างกราฟของฟังก์ชัน $f(x)=\\frac{12}{x^{2}+2x+4}$ (หาช่วงเพิ่ม/ลด, เว้า, จุดวิกฤต, จุดเปลี่ยนเว้า, เส้นกำกับ).\n\n"
    "Your task:\n"
    "1) Generate ONE NEW curve sketching problem that follows the same logic: find f', f'', analyze signs for intervals, find critical/inflection points, and find asymptotes.\n"
    "2) The problem must be 'ถึกขึ้น' (significantly more tedious) than the original.\n"
    "   - Use a non-polynomial function, for example, involving $e^x$ or $\\ln x$ combined with a polynomial (e.g., $f(x) = x^2 e^{-x}$ or $f(x) = \\frac{\\ln x}{x}$). \n"
    "   - The complexity must come from the derivatives. The second derivative $f''(x)$ should be complex, and solving $f''(x)=0$ should require non-trivial algebra.\n"
    "   - The critical points and inflection points should be non-integers (e.g., $x=e^{3/2}$ or $x=2+\\sqrt{2}$).\n"
    "3) The question must ask for all the same components: (a) intervals of increase/decrease, (b) intervals of concavity, (c) critical points and inflection points, and (d) all asymptotes.\n"
    "4) Solve it completely, showing all analysis steps.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Asymptotes, Derivative 1, Critical points, Inc/Dec, Derivative 2, Concavity, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only for f(x) = lnx / x):\n"
    "  \"\\\\begin{align*}\n"
    "     f(x) &= \\\\frac{\\\\ln x}{x} \\\\text{, Domain: } x > 0 \\\\\n"
    "     \\\\text{Asymptotes:} & \\\\\n"
    "     \\\\lim_{x \\to 0^+} \\frac{\\\\ln x}{x} &= \\\\frac{-\\infty}{0^+} = -\\infty \\\\Rightarrow \\\\text{Vertical Asymptote at } x=0 \\\\\n"
    "     \\\\lim_{x \\to \\infty} \\frac{\\\\ln x}{x} &\\\\overset{L'H}{=} \\\\lim_{x \\to \\infty} \\\\frac{1/x}{1} = 0 \\\\Rightarrow \\\\text{Horizontal Asymptote at } y=0 \\\\\n"
    "     \\\\text{Derivative 1:} & \\\\\n"
    "     f'(x) &= \\\\frac{x(1/x) - (\\\\ln x)(1)}{x^2} = \\\\frac{1 - \\\\ln x}{x^2} \\\\\n"
    "     \\\\text{Set } f'(x) &= 0 \\\\Rightarrow 1 - \\\\ln x = 0 \\\\Rightarrow \\\\ln x = 1 \\\\Rightarrow x = e \\\\\n"
    "     \\\\text{Critical Point:} & x=e \\\\text{ (Local Max at } (e, 1/e)) \\\\\n"
    "     \\\\text{Increasing on } (0, e), & \\\\text{ Decreasing on } (e, \\infty) \\\\\n"
    "     \\\\text{Derivative 2:} & \\\\\n"
    "     f''(x) &= \\\\frac{x^2(-1/x) - (1 - \\\\ln x)(2x)}{x^4} = \\\\frac{-x - 2x + 2x \\\\ln x}{x^4} = \\\\frac{2 \\\\ln x - 3}{x^3} \\\\\n"
    "     \\\\text{Set } f''(x) &= 0 \\\\Rightarrow 2 \\\\ln x - 3 = 0 \\\\Rightarrow \\ln x = 3/2 \\\\Rightarrow x = e^{3/2} \\\\\n"
    "     \\\\text{Inflection Point at } &x = e^{3/2} \\\\\n"
    "     \\\\text{Concave Down on } (0, e^{3/2}), & \\\\text{ Concave Up on } (e^{3/2}, \\infty)\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{กำหนดให้ } f(x) = ... \\\\text{ จงวิเคราะห์ฟังก์ชันนี้โดยหา: (a) ช่วงเพิ่ม/ลด, (b) ช่วงเว้าบน/ล่าง, (c) จุดวิกฤตและจุดเปลี่ยนเว้า, และ (d) เส้นกำกับทั้งหมด}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),
"B3: Growth Model Analysis": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "B3. (d) ให้ $P(t) = \\frac{M}{1+Ae^{-t/T}}$ จงหาเวลา $t$ ที่ทำให้อัตราการเติบโตของประชากร ($P'(t)$) มีค่าสูงสุด[cite: 38, 50].\n\n"
    "Your task:\n"
    "1) Generate ONE NEW growth model problem that follows the same logic: finding the time of maximum growth rate (i.e., finding the inflection point by setting $P''(t)=0$).\n"
    "2) The problem must be 'ถึกขึ้น' (significantly more tedious). Use the **Gompertz function** instead of the Logistic function. \n"
    "   - Example form: $P(t) = K \\cdot e^{-A e^{-rt}}$\n"
    "   - Finding $P'(t)$ (the growth rate) will require a complex chain rule.\n"
    "   - Finding $P''(t)$ (to maximize the rate) will require a very complex product rule on top of chain rules.\n"
    "3. Provide specific values for the constants (K, A, r) and ask for the time $t$ when the growth rate $P'(t)$ is maximal, AND the population $P(t)$ at that time.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Growth Rate, Set, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only for Gompertz):\n"
    "  \"\\\\begin{align*}\n"
    "     P(t) &= 1000 e^{-5e^{-0.1t}} \\\\\n"
    "     \\\\text{Growth Rate } R(t) = P'(t) &= 1000 \\\\cdot e^{-5e^{-0.1t}} \\\\cdot \\\\frac{d}{dt}(-5e^{-0.1t}) \\\\\n"
    "     P'(t) &= 1000 \\\\cdot e^{-5e^{-0.1t}} \\\\cdot (-5e^{-0.1t}) \\\\cdot (-0.1) \\\\\n"
    "     P'(t) &= 500 \\\\cdot e^{-0.1t} \\\\cdot e^{-5e^{-0.1t}} \\\\\n"
    "     \\\\text{Find max rate by setting } P''(t) = 0. & \\\\text{ Let } R(t) = P'(t). \\\\text{ Find } R'(t) \\\\text{ (Product Rule):} \\\\\n"
    "     R'(t) &= 500 \\\\left[ (e^{-0.1t}(-0.1)) \\\\cdot (e^{-5e^{-0.1t}}) + (e^{-0.1t}) \\\\cdot (e^{-5e^{-0.1t}} \\\\cdot 5e^{-0.1t} \\\\cdot 0.1) \\\\right] \\\\\n"
    "     R'(t) &= 500 \\\\cdot e^{-0.1t} \\\\cdot e^{-5e^{-0.1t}} \\\\left[ -0.1 + 0.5e^{-0.1t} \\\\right] \\\\\n"
    "     \\\\text{Set } R'(t) = 0. & \\\\text{ The exponential terms are always > 0.} \\\\\n"
    "     -0.1 + 0.5e^{-0.1t} &= 0 \\\\\n"
    "     0.5e^{-0.1t} &= 0.1 \\\\\n"
    "     e^{-0.1t} &= \\\\frac{0.1}{0.5} = 0.2 = \\\\frac{1}{5} \\\\\n"
    "     -0.1t &= \\\\ln(1/5) = -\\\\ln(5) \\\\\n"
    "     t &= 10 \\\\ln(5) \\\\\n"
    "     \\\\text{Population at this time:} & \\\\\n"
    "     P(10 \\\\ln 5) &= 1000 e^{-5e^{-0.1(10 \\ln 5)}} = 1000 e^{-5e^{-\\ln 5}} \\\\\n"
    "     &= 1000 e^{-5(1/5)} = 1000 e^{-1} = \\\\frac{1000}{e}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{การเติบโตของประชากรกลุ่มหนึ่งเป็นไปตามสมการ Gompertz } P(t) = ... \\\\text{ จงหาเวลา } t \\\\text{ ที่อัตราการเติบโตของประชากรมีค่าสูงสุด และหาจำนวนประชากร ณ เวลานั้น}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),
"C1: Area Between Curves": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "C1. จงเขียนอินทิกรัลแสดงพื้นที่ของบริเวณปิดล้อมด้วยแส้นโค้งต่อไปนี้\n"
    "(a) $y=x^{2}+2,$ $y=-x-1$, $x=-1;$, $x=1$ (Simple Top-Bottom)\n"
    "(b) $\\frac{x^{2}}{4}+y^{2}=2, x=2y^{2}$ (Simple Right-Left)\n\n"
    "Your task:\n"
    "1) Generate ONE NEW area problem that follows the same core logic (find intersections, set up $\\int (f-g)$) but is significantly harder.\n"
    "2) The problem must be 'ถึกขึ้น' (more tedious) in two ways:\n"
    "   - The functions must **cross over** multiple times, forcing the total area to be a SUM of multiple integrals (e.g., $\\int_{a}^{b} (f-g) dx + \\int_{b}^{c} (g-f) dx$).\n"
    "   - The intersection points should be non-trivial (e.g., cubic roots, or involving square roots).\n"
    "3) The AI must **solve for the total area completely**, not just set up the integral.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Intersections, Region 1, Region 2, Total Area, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Find area between } y &= x^3 - 3x \\\\text{ and } y = x. \\\\\n"
    "     \\\\text{Intersections: } & x^3 - 3x = x \\\\Rightarrow x^3 - 4x = 0 \\\\\n"
    "     & x(x^2 - 4) = 0 \\\\Rightarrow x = -2, 0, 2. \\\\\n"
    "     \\\\text{This creates two regions.} \\\\\n"
    "     \\\\text{Region 1 (on } [-2, 0]): & \\\\text{ Test } x=-1: (x^3-3x) = 2, (x) = -1. \\\\Rightarrow x^3-3x \\\\text{ is on top.} \\\\\n"
    "     A_1 &= \\\\int_{-2}^{0} ((x^3 - 3x) - (x)) \\\\, dx = \\\\int_{-2}^{0} (x^3 - 4x) \\\\, dx \\\\\n"
    "         &= \\\\left[ \\\\frac{x^4}{4} - 2x^2 \\\\right]_{-2}^{0} = (0) - (\\\\frac{16}{4} - 2(4)) = -(4 - 8) = 4 \\\\\n"
    "     \\\\text{Region 2 (on } [0, 2]): & \\\\text{ Test } x=1: (x^3-3x) = -2, (x) = 1. \\\\Rightarrow x \\\\text{ is on top.} \\\\\n"
    "     A_2 &= \\\\int_{0}^{2} (x - (x^3 - 3x)) \\\\, dx = \\\\int_{0}^{2} (4x - x^3) \\\\, dx \\\\\n"
    "         &= \\\\left[ 2x^2 - \\\\frac{x^4}{4} \\\\right]_{0}^{2} = (2(4) - \\\\frac{16}{4}) - (0) = (8 - 4) = 4 \\\\\n"
    "     \\\\text{Total Area } A &= A_1 + A_2 = 4 + 4 = 8\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาพื้นที่ทั้งหมดของบริเวณที่ปิดล้อมด้วยเส้นโค้ง } y = ... \\\\text{ และ } y = ...\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),
"C2: Applied Integration": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "C2. Given a graph of $v_A(t)$ and $v_B(t)$. Questions are conceptual:\n"
    "(a) Interpret the area under $v_A$. \n"
    "(b) Which car is ahead? [cite: 63]\n"
    "(c) Interpret the shaded area between them. \n\n"
    "Your task:\n"
    "1) Generate ONE NEW problem that uses the same logic (integral of $v$ is displacement; integral of $v_A - v_B$ is relative distance) but requires **direct calculation** (making it 'ถึกขึ้น').\n"
    "2) Do NOT provide a graph. Provide two explicit velocity functions, $v_A(t)$ and $v_B(t)$.\n"
    "3) Make the functions non-trivial. At least one function must require **integration by parts** or a complex substitution to integrate.\n"
    "4) The question must ask for: (a) The total distance traveled by one car at a specific time $T$, and (b) The distance *between* the two cars at that same time $T$.\n"
    "5) Solve it completely, showing all integration steps.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Distance, By Parts, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Given } v_A(t) = t e^{-t} & \\\\text{ and } v_B(t) = t^2. \\\\text{ Both start at } s(0)=0. \\\\\n"
    "     \\\\text{(a) Distance of Car A at } t=2: & \\\\\n"
    "     s_A(2) &= \\\\int_0^2 t e^{-t} \\\\, dt \\\\\n"
    "     \\\\text{By Parts: } & u=t, \\\\, dv=e^{-t} dt \\\\Rightarrow du=dt, \\\\, v=-e^{-t} \\\\\n"
    "     s_A(2) &= \\\\left[ -t e^{-t} \\\\right]_0^2 - \\\\int_0^2 -e^{-t} \\\\, dt \\\\\n"
    "            &= (-2e^{-2} - 0) + \\\\int_0^2 e^{-t} \\\\, dt \\\\\n"
    "            &= -2e^{-2} + \\\\left[ -e^{-t} \\\\right]_0^2 \\\\\n"
    "            &= -2e^{-2} + (-e^{-2} - (-e^0)) = -3e^{-2} + 1 \\\\\n"
    "     \\\\text{(b) Distance between cars at } t=2: & \\\\\n"
    "     s_B(2) &= \\\\int_0^2 t^2 \\\\, dt = \\\\left[ \\\\frac{t^3}{3} \\\\right]_0^2 = \\\\frac{8}{3} \\\\\n"
    "     \\\\text{Relative Distance } D &= s_B(2) - s_A(2) \\\\\n"
    "     D &= \\\\frac{8}{3} - (1 - 3e^{-2}) = \\\\frac{5}{3} + 3e^{-2}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{รถยนต์ A และ B เริ่มเคลื่อนที่จากหยุดนิ่ง ... } v_A(t) = ... \\\\text{ และ } v_B(t) = ... \\\\text{ (a) จงหาระยะทางที่รถ ... เคลื่อนที่ได้ ... (b) จงหาระยะห่างระหว่างรถทั้งสอง ...}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),
"C3: Volume by Cross-Section": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "C3. จงหาปริมาตรของทรงตันที่มีฐานเป็นบริเวณ R ปิดล้อมด้วย $y=x^{2}-1$ และ $y=x+1$, และภาคตัดที่ตั้งฉากกับแกน X เป็นรูปสี่เหลี่ยมจัตุรัส.\n\n"
    "Your task:\n"
    "1) Generate ONE NEW volume by cross-section problem that follows the same logic: $V = \\int_a^b A(x) \\, dx$, where $A(x)$ is the cross-sectional area.\n"
    "2) The problem must be 'ถึกขึ้น' (significantly more tedious) by changing the cross-section.\n"
    "   - Instead of a square (where $A = s^2$), the cross-section must be a shape where the area formula is more complex, e.g., a **semicircle** (where $A = \\frac{1}{2}\\pi r^2 = \\frac{\\pi}{8} s^2$), or an **equilateral triangle** (where $A = \\frac{\\sqrt{3}}{4} s^2$), or an **isosceles right triangle with hypotenuse on the base** (where $A = \\frac{1}{4} s^2$).\n"
    "   - The base region R can be the same or slightly different, but the integral $\\int A(x) \\, dx$ must be a complex polynomial integration (requiring expansion, etc.).\n"
    "3) The AI must solve for the total volume completely.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Base, Intersections, Side, Area, Volume, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Base curves: } y = 4 - x^2 \\\\text{ and } y = 0. \\\\\n"
    "     \\\\text{Intersections: } & 4 - x^2 = 0 \\\\Rightarrow x = -2, 2. \\\\\n"
    "     \\\\text{Side length } s(x) &= (\\\\text{Top}) - (\\\\text{Bottom}) = (4 - x^2) - 0 = 4 - x^2. \\\\\n"
    "     \\\\text{Cross-section:} & \\\\text{Semicircle with diameter } s(x). \\\\\n"
    "     \\\\text{Radius } r(x) &= \\\\frac{s(x)}{2} = \\\\frac{4 - x^2}{2}. \\\\\n"
    "     \\\\text{Area } A(x) &= \\\\frac{1}{2} \\\\pi (r(x))^2 = \\\\frac{1}{2} \\\\pi \\\\left( \\\\frac{4 - x^2}{2} \\\\right)^2 \\\\\n"
    "     A(x) &= \\\\frac{\\\\pi}{8} (4 - x^2)^2 = \\\\frac{\\\\pi}{8} (16 - 8x^2 + x^4) \\\\\n"
    "     \\\\text{Volume } V &= \\\\int_{-2}^{2} A(x) \\\\, dx = \\\\frac{\\\\pi}{8} \\\\int_{-2}^{2} (16 - 8x^2 + x^4) \\\\, dx \\\\\n"
    "     \\\\text{(Even function)} &= 2 \\\\cdot \\\\frac{\\\\pi}{8} \\\\left[ 16x - \\\\frac{8x^3}{3} + \\\\frac{x^5}{5} \\\\right]_{0}^{2} \\\\\n"
    "     &= \\\\frac{\\\\pi}{4} \\\\left[ (16(2) - \\\\frac{8(8)}{3} + \\\\frac{32}{5}) - 0 \\\\right] \\\\\n"
    "     &= \\\\frac{\\\\pi}{4} \\\\left( 32 - \\\\frac{64}{3} + \\\\frac{32}{5} \\\\right) = \\\\frac{\\\\pi}{4} \\\\left( \\\\frac{480 - 320 + 96}{15} \\\\right) \\\\\n"
    "     &= \\\\frac{\\\\pi}{4} \\\\left( \\\\frac{256}{15} \\\\right) = \\\\frac{64\\\\pi}{15}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาปริมาตรของทรงตันที่มีฐานเป็นบริเวณ R ... และภาคตัดที่ตั้งฉากกับแกน X เป็นรูป ...}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),
"C4: Volume by Washers": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "C4. จงหาปริมาตรของทรงตันที่ได้จากการหมุนบริเวณ R...\n"
    "(a) R ปิดล้อมด้วย $y=\\sqrt{x}, y=0, x=4$, รอบแกน X (Disk Method) [cite: 68]\n"
    "(b) R ปิดล้อมด้วย $8y=x^2, y=\\sqrt{x}$, รอบเส้นตรง $x=-1$ (Washer Method) \n\n"
    "Your task:\n"
    "1) Generate ONE NEW volume of revolution problem that uses the **Washer Method** logic (like C4b).\n"
    "2) The problem must be 'ถึกขึ้น' (significantly more tedious) in two ways:\n"
    "   - The region R should be bounded by **non-polynomial functions** (e.g., trigonometric, exponential).\n"
    "   - The axis of revolution must be a **horizontal or vertical line *off* the main axes** (e.g., $y=c$ or $x=c$), forcing a complex setup for the outer radius $R$ and inner radius $r$.\n"
    "   - The resulting integral $\\int \\pi (R(x)^2 - r(x)^2) \\, dx$ must require non-trivial integration (e.g., using **trig identities / power-reduction formulas** to solve).\n"
    "3) The AI must solve for the total volume completely.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Region, Axis, Washer, Radius, Use, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Region R bounded by } y = \\\\sin x, y = 0, \\\\text{ from } x=0 \\\\text{ to } x=\\\\pi. \\\\\n"
    "     \\\\text{Axis of Revolution: } y = 2. \\\\\n"
    "     \\\\text{Washer Method (dx):} \\\\\n"
    "     \\\\text{Outer Radius } R(x) &= (\\\\text{axis}) - (\\\\text{far curve}) = 2 - 0 = 2 \\\\\n"
    "     \\\\text{Inner Radius } r(x) &= (\\\\text{axis}) - (\\\\text{near curve}) = 2 - \\\\sin x \\\\\n"
    "     V &= \\\\int_0^{\\\\pi} \\\\pi ( [R(x)]^2 - [r(x)]^2 ) \\\\, dx \\\\\n"
    "     V &= \\\\pi \\\\int_0^{\\\\pi} ( (2)^2 - (2 - \\\\sin x)^2 ) \\\\, dx \\\\\n"
    "     V &= \\\\pi \\\\int_0^{\\\\pi} ( 4 - (4 - 4\\\\sin x + \\\\sin^2 x) ) \\\\, dx \\\\\n"
    "     V &= \\\\pi \\\\int_0^{\\\\pi} ( 4\\\\sin x - \\\\sin^2 x ) \\\\, dx \\\\\n"
    "     \\\\text{(Use power reduction: } \\\\sin^2 x = \\\\frac{1 - \\\\cos(2x)}{2}) \\\\\n"
    "     V &= \\\\pi \\\\int_0^{\\\\pi} ( 4\\\\sin x - \\\\frac{1}{2}(1 - \\\\cos(2x)) ) \\\\, dx \\\\\n"
    "     V &= \\\\pi \\\\left[ -4\\\\cos x - \\\\frac{1}{2}x + \\\\frac{1}{4}\\\\sin(2x) \\\\right]_0^{\\\\pi} \\\\\n"
    "     V &= \\\\pi \\\\left[ (-4\\\\cos \\\\pi - \\\\frac{\\\\pi}{2} + \\\\frac{1}{4}\\\\sin(2\\\\pi)) - (-4\\\\cos 0 - 0 + 0) \\\\right] \\\\\n"
    "     V &= \\\\pi \\\\left[ (-4(-1) - \\\\frac{\\\\pi}{2} + 0) - (-4(1)) \\\\right] \\\\\n"
    "V &= \\\\pi \\\\left[ 4 - \\\\frac{\\\\pi}{2} + 4 \\\\right] = 8\\\\pi - \\\\frac{\\\\pi^2}{2}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาปริมาตรของทรงตันที่เกิดจากการหมุนบริเวณ R ที่ปิดล้อมด้วย ... รอบเส้นตรง ...}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),
"D1: Trig Integrals": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "D1(c) จงหา $\\int \\sin^4(x/3) dx$\n"
    "D1(a) จงหา $\\int \\sin^5 x \\cos^4 x \\, dx$\n\n"
    "Your task:\n"
    "1) Generate ONE NEW trigonometric integral problem that is 'ถึกขึ้น' (more tedious) than the models.\n"
    "2) The logic must be the **'both powers are even' case** (like D1c).\n"
    "   - This forces the use of power-reduction (half-angle) formulas like $\\sin^2 \\theta = \\frac{1-\\cos(2\\theta)}{2}$.\n"
    "   - To make it 'ถึก', the problem must require **nested applications** of this formula. For example, $\\int \\sin^6(x) \\, dx$ or $\\int \\sin^4(x) \\cos^2(x) \\, dx$. The expansion will create new $\\cos^2(...)$ or $\\cos^3(...)$ terms that need further reduction/integration.\n"
    "   - Do NOT generate a simple 'odd power' case (like D1a).\n"
    "3) The AI must solve the integral completely, showing all algebraic expansions and substitutions.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Use, Let, Expand, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example for $\\sin^4 x$):\n"
    "  \"\\\\begin{align*}\n"
    "     I &= \\\\int \\\\sin^4 x \\\\, dx = \\\\int (\\\\sin^2 x)^2 \\\\, dx \\\\\n"
    "       &= \\\\int \\\\left( \\\\frac{1 - \\\\cos(2x)}{2} \\\\right)^2 \\\\, dx \\\\\n"
    "       &= \\\\frac{1}{4} \\\\int (1 - 2\\\\cos(2x) + \\\\cos^2(2x)) \\\\, dx \\\\\n"
    "     \\\\text{Use power reduction again on } & \\\\cos^2(2x) = \\\\frac{1 + \\\\cos(4x)}{2} \\\\\n"
    "     I &= \\\\frac{1}{4} \\\\int (1 - 2\\\\cos(2x) + \\\\frac{1 + \\\\cos(4x)}{2}) \\\\, dx \\\\\n"
    "       &= \\\\frac{1}{4} \\\\int (\\\\frac{3}{2} - 2\\\\cos(2x) + \\\\frac{1}{2}\\\\cos(4x)) \\\\, dx \\\\\n"
    "       &= \\\\frac{1}{4} \\\\left[ \\\\frac{3}{2}x - \\\\sin(2x) + \\\\frac{1}{8}\\\\sin(4x) \\\\right] + C \\\\\n"
    "       &= \\\\frac{3}{8}x - \\\\frac{1}{4}\\\\sin(2x) + \\\\frac{1}{32}\\\\sin(4x) + C\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาค่าของ } \\\\int ... dx\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"D2:  Integration by Parts": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "D2(b) จงหา $\\int e^{x}(ln~e^{x})^{2}dx$ (simplifies to $\\int x^2 e^x dx$)\n"
    "D2(d) จงหา $\\int x^{2}sin~x~dx$\n\n"
    "Your task:\n"
    "1) Generate ONE NEW integral problem that follows the most complex logic from D2: **repeated Integration by Parts (IBP)**.\n"
    "2) The problem must be 'ถึกขึ้น' (more tedious). It must require at least **two applications of IBP**.\n"
    "   - Option A (Tabular): A product of $x^n$ (where $n=2$ or $3$) and $e^x$, $\\sin(kx)$, or $\\cos(kx)$. E.g., $\\int x^3 \\cos(2x) \\, dx$.\n"
    "   - Option B (Looping): A product of $e^{ax}$ and $\\sin(bx)$ or $\\cos(bx)$. E.g., $\\int e^{-x} \\cos(3x) \\, dx$. This type is harder as it requires IBP twice and then solving algebraically for the integral.\n"
    "   - Please choose one of these harder styles.\n"
    "3) The AI must solve the integral completely, showing all steps of the repeated IBP.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, IBP 1, IBP 2, Solve for I, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example for $\\int x^2 \\sin x dx$):\n"
    "  \"\\\\begin{align*}\n"
    "     I &= \\\\int x^2 \\\\sin x \\\\, dx \\\\\n"
    "     \\\\text{IBP 1: } & u = x^2, \\\\, dv = \\\\sin x \\\\, dx \\\\\n"
    "                & du = 2x \\\\, dx, \\\\, v = -\\\\cos x \\\\\n"
    "     I &= -x^2 \\\\cos x - \\\\int (- \\\\cos x)(2x \\\\, dx) \\\\\n"
    "       &= -x^2 \\\\cos x + 2 \\\\int x \\\\cos x \\\\, dx \\\\\n"
    "     \\\\text{IBP 2: } & u = x, \\\\, dv = \\\\cos x \\\\, dx \\\\\n"
    "                & du = dx, \\\\, v = \\\\sin x \\\\\n"
    "     I &= -x^2 \\\\cos x + 2 \\\\left[ x \\\\sin x - \\\\int \\\\sin x \\\\, dx \\\\right] \\\\\n"
    "       &= -x^2 \\\\cos x + 2x \\\\sin x - 2(-\\\\cos x) + C \\\\\n"
    "       &= -x^2 \\\\cos x + 2x \\\\sin x + 2\\\\cos x + C\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาค่าของ } \\\\int ... dx\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"D3: Applied IBP": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "D3(a) ให้ $\\int_{0}^{3}(2x+1)f''(x) dx=10$ และ $f'(0)=f'(3)=1$ แล้ว จงหา $f(3)-f(0)$\n"
    "D3(b) ให้ $f(1)=2, f(4)=7, f'(1)=5, f'(4)=3$ ... จงหาค่าของ $\\int_{1}^{4}xf''(x)dx$\n\n"
    "Your task:\n"
    "1) Generate ONE NEW problem that follows the core logic of D3: using Integration by Parts on a definite integral with an unknown function $f(x)$ and given boundary values.\n"
    "2) The problem must be 'ถึกขึ้น' (significantly more tedious) by requiring **TWO applications of IBP**.\n"
    "   - The integral should be of the form $\\int_a^b (x^2+c) f''(x) \\, dx$.\n"
    "   - The target of the question must be $\\int_a^b f(x) dx$. This is harder than the original problems because it requires the user to complete both IBP steps and then algebraically isolate the final integral.\n"
    "3) The AI must provide all necessary values: the value of the main integral $\\int_a^b ...$, and all boundary values needed ($f(a), f(b), f'(a), f'(b)$).\n"
    "4) Solve it completely, showing all IBP steps and the final algebra to find $\\int_a^b f(x) dx$.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, IBP 1, IBP 2, Given, Solve for, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Given: } & \\\\int_0^1 x^2 f''(x) dx = 10 \\\\\n"
    "     & f(0)=1, f(1)=3, f'(0)=2, f'(1)=5 \\\\\n"
    "     \\\\text{Let } I &= \\\\int_0^1 x^2 f''(x) dx \\\\\n"
    "     \\\\text{IBP 1: } & u = x^2, \\\\, dv = f''(x) dx \\\\\n"
    "                & du = 2x dx, \\\\, v = f'(x) \\\\\n"
    "     I &= \\\\left[ x^2 f'(x) \\\\right]_0^1 - \\\\int_0^1 f'(x) (2x dx) \\\\\n"
    "     10 &= ( (1)^2 f'(1) - (0)^2 f'(0) ) - 2 \\\\int_0^1 x f'(x) dx \\\\\n"
    "     10 &= ( 1(5) - 0 ) - 2 \\\\int_0^1 x f'(x) dx \\\\\n"
    "     10 &= 5 - 2 \\\\int_0^1 x f'(x) dx \\\\\n"
    "     2 \\\\int_0^1 x f'(x) dx &= -5 \\\\Rightarrow \\\\int_0^1 x f'(x) dx = -2.5 \\\\\n"
    "     \\\\text{IBP 2 (on the new integral):} & \\\\\n"
    "     \\\\text{Let } J &= \\\\int_0^1 x f'(x) dx \\\\\n"
    "     & u = x, \\\\, dv = f'(x) dx \\\\\n"
    "     & du = dx, \\\\, v = f(x) \\\\\n"
    "     J &= \\\\left[ x f(x) \\\\right]_0^1 - \\\\int_0^1 f(x) dx \\\\\n"
    "     -2.5 &= ( (1)f(1) - (0)f(0) ) - \\\\int_0^1 f(x) dx \\\\\n"
    "     -2.5 &= ( 1(3) - 0 ) - \\\\int_0^1 f(x) dx \\\\\n"
    "     -2.5 &= 3 - \\\\int_0^1 f(x) dx \\\\\n"
    "     \\\\int_0^1 f(x) dx &= 3 - (-2.5) = 5.5 \\\\\n"
    "     \\\\text{Answer: } 5.5\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{กำหนดให้ } \\\\int_a^b ... = ... \\\\text{ และ } f(a)=..., f(b)=..., f'(a)=..., f'(b)=... \\\\text{ จงหาค่าของ } \\\\int_a^b f(x) dx\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"D4: Shell Method (Harder Split Region)": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "D4. R is bounded by $x=\\sqrt{y}$, $x=\\sqrt{4y-12}$ and the Y-axis. Find the volume of revolution using the Method of Cylindrical Shells when rotating around:\n"
    "(b) the X-axis [This forces a split integral $\\int_0^3 ... dy + \\int_3^4 ... dy$]\n\n"
    "Your task:\n"
    "1) Generate ONE NEW volume problem that follows the **exact logic of D4(b)**.\n"
    "2) The problem must be 'ถึกขึ้น' (more tedious) by creating a new Region R (bounded by $x=f(y)$, $x=g(y)$, and the Y-axis) that **MUST be split into two parts** when integrating with respect to $y$.\n"
    "   - Example: A region bounded by $x=0$, $x=\\sqrt{y-1}$ (starts at y=1), and $x=y-3$ (starts at y=3). This region splits at $y=3$.\n"
    "3) The question MUST ask for the volume using the **Method of Cylindrical Shells** rotating around the **X-axis** (or a parallel line like $y=-1$).\n"
    "4. This setup forces the solution to be a sum of two integrals: $V = \\int_a^c 2\\pi y (f(y) - g(y)) dy + \\int_c^d 2\\pi y (f(y) - h(y)) dy$.\n"
    "5) The functions $f(y), g(y)$ should make the resulting integrals non-trivial (e.g., requiring u-substitution like $\\int y\\sqrt{y-1} dy$).\n"
    "6) Solve it completely, showing the setup of both integrals and the final calculation.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Region, Axis, Shells, Radius, Height, Region 1, Region 2, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Region R bounded by } x=0, x=\\sqrt{y-1} \\\\text{ (for } y \\ge 1), \\\\text{ and } x=y-3 \\\\text{ (for } y \\ge 3). \\\\\n"
    "     \\\\text{Intersections: } \\\\sqrt{y-1} = y-3 \\\\Rightarrow y-1 = y^2-6y+9 \\\\Rightarrow y^2-7y+10=0 \\\\\n"
    "     (y-2)(y-5)=0. \\\\text{ $y=2$ (no, $x$ values mismatch), $y=5$ (yes, $x=2$).} \\\\\n"
    "     \\\\text{Region splits at } y=3. \\\\\n"
    "     \\\\text{Axis: } X-axis. \\\\text{ Method: Shells (dy).} \\\\\n"
    "     \\\\text{Radius } r = y. \\\\\n"
    "     \\\\text{Region 1 (} 1 \\le y \\le 3): & \\\\text{ Height } h_1 = x_{right} - x_{left} = \\sqrt{y-1} - 0 \\\\\n"
    "     V_1 &= \\\\int_1^3 2\\pi y \\sqrt{y-1} \\\\, dy \\\\\n"
    "     \\\\text{Region 2 (} 3 \\le y \\le 5): & \\\\text{ Height } h_2 = x_{right} - x_{left} = \\sqrt{y-1} - (y-3) \\\\\n"
    "     V_2 &= \\\\int_3^5 2\\pi y (\\\\sqrt{y-1} - y + 3) \\\\, dy \\\\\n"
    "     \\\\text{Solve } V_1: & \\\\text{ Let } u=y-1 \\\\Rightarrow y=u+1, du=dy \\\\\n"
    "     V_1 &= 2\\\\pi \\\\int_0^2 (u+1)\\\\sqrt{u} \\\\, du = 2\\\\pi \\\\int_0^2 (u^{3/2} + u^{1/2}) \\\\, du \\\\\n"
    "         &= 2\\\\pi \\\\left[ \\\\frac{2}{5}u^{5/2} + \\\\frac{2}{3}u^{3/2} \\\\right]_0^2 = 2\\\\pi (\\\\frac{2}{5}(4\\\\sqrt{2}) + \\\\frac{2}{3}(2\\\\sqrt{2})) = ... \\\\\n"
    "     \\\\text{Solve } V_2: & \\\\text{ (Similarly complex)} ... \\\\\n"
    "     V &= V_1 + V_2 = ... \\\\text{ (Final Answer)}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{ให้ R เป็นบริเวณที่ปิดล้อมด้วย ... จงหาปริมาตร ... โดยวิธีเปลือกทรงกระบอก}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"E1: Advanced Integration (Random Logic)": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model (Section E1) is a collection of various advanced integration techniques.\n\n"
    "Your task:\n"
    "1) **First, randomly select ONE logic** from the following 6 categories:\n"
    "   - CAT 1: Secant/Tangent integral with an even secant power or an odd tangent power (like E1a, E1c, E1g).\n"
    "   - CAT 2: Trigonometric Substitution (like E1l, E1n, $\\int x^3 \\sqrt{a^2-x^2} dx$).\n"
    "   - CAT 3: Completing the Square, then Trig Substitution (like E1m, E1o).\n"
    "   - CAT 4: Product-to-Sum formulas (like E1j, E1k).\n"
    "   - CAT 5: Special u-substitution (like E1i, $\\int \\frac{\\cos(\\ln x)}{x} dx$).\n"
    "   - CAT 6: Special reduction/case (like E1d: $\\int \\csc^n x dx$ or E1e: $\\int \\tan^n x dx$).\n"
    "2) Generate ONE NEW integral problem based *only* on the category you selected.\n"
    "3) Make the problem 'ถึกขึ้น' (more tedious) than the originals:\n"
    "   - CAT 1: Use high powers (e.g., $\\int \\sec^5 x \\tan^7 x dx$).\n"
    "   - CAT 2: Make the integral require a complex final substitution (e.g., $\\int \\frac{x^3}{\\sqrt{x^2+4}} dx$).\n"
    "   - CAT 3: Make the numerator complex (e.g., $\\int \\frac{x+2}{\\sqrt{x^2-2x-3}} dx$).\n"
    "   - CAT 4: Use a triple product (like E1k, e.g., $\\int \\cos(x)\\cos(2x)\\cos(4x) dx$).\n"
    "   - CAT 5/6: Use a slightly more obscure substitution or a higher power for reduction.\n"
    "4) Solve the integral completely, showing all steps (u-sub, trig sub, IBP, formulas, etc.).\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Use, Trig Sub, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example for CAT 3):\n"
    "  \"\\\\begin{align*}\n"
    "     I &= \\\\int \\\\frac{x+2}{\\\\sqrt{x^2-2x-3}} \\\\, dx = \\\\int \\\\frac{x+2}{\\\\sqrt{(x-1)^2 - 4}} \\\\, dx \\\\\n"
    "     \\\\text{Let } u &= x-1 \\\\Rightarrow x=u+1, \\\\, du=dx \\\\\n"
    "     I &= \\\\int \\\\frac{(u+1)+2}{\\\\sqrt{u^2 - 4}} \\\\, du = \\\\int \\\\frac{u}{\\\\sqrt{u^2 - 4}} \\\\, du + \\\\int \\\\frac{3}{\\\\sqrt{u^2 - 4}} \\\\, du \\\\\n"
    "     \\\\text{Part 1 (u-sub): } & \\\\int \\\\frac{u}{\\\\sqrt{u^2 - 4}} \\\\, du = \\\\sqrt{u^2 - 4} \\\\\n"
    "     \\\\text{Part 2 (Trig Sub): } & u = 2\\\\sec\\\\theta \\\\Rightarrow du = 2\\\\sec\\\\theta\\\\tan\\\\theta \\\\, d\\\\theta \\\\\n"
    "     \\\\int \\\\frac{3}{\\\\sqrt{4\\\\sec^2\\\\theta - 4}} & (2\\\\sec\\\\theta\\\\tan\\\\theta \\\\, d\\\\theta) = \\\\int \\\\frac{3}{2\\\\tan\\\\theta} (2\\\\sec\\\\theta\\\\tan\\\\theta \\\\, d\\\\theta) \\\\\n"
    "     &= 3 \\\\int \\\\sec\\\\theta \\\\, d\\\\theta = 3 \\\\ln|\\\\sec\\\\theta + \\\\tan\\\\theta| \\\\\n"
    "     &= 3 \\\\ln|\\\\frac{u}{2} + \\\\frac{\\\\sqrt{u^2-4}}{2}| \\\\\n"
    "     I &= \\\\sqrt{(x-1)^2-4} + 3 \\\\ln|\\\\frac{x-1}{2} + \\\\frac{\\\\sqrt{x^2-2x-3}}{2}| + C\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาค่าของ } \\\\int ... dx\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"E2: IBP on Inverse Trig": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "E2(a) $\\int_{0}^{1/2}sin^{-1}(x)dx$\n"
    "E2(b) $\\int_{-1}^{1}x~tan^{-1}(x)dx$\n"
    "E2(c) $\\int tan^{-1}(\\sqrt{x})dx$\n\n"
    "Your task:\n"
    "1) Generate ONE NEW integral problem that follows the core logic of E2a/E2b: **Integration by Parts (IBP) on an Inverse Trigonometric Function**.\n"
    "2) The problem must be 'ถึกขึ้น' (significantly more tedious).\n"
    "   - The integrand should be a product $x^n \cdot f(x)$, where $f(x)$ is an inverse trig function (like $\\tan^{-1}(x)$ or $\\sin^{-1}(x)$) and $n$ is an integer $n \\ge 2$.\n"
    "   - This setup is harder because the resulting integral $\\int v \\, du$ (after the first IBP) will be a rational function that requires **polynomial long division** before it can be solved.\n"
    "3) The AI must solve the integral completely, showing the IBP step, the long division, and the final integration.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, IBP, Long Division, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example for $\\int x^2 \\tan^{-1}(x) dx$):\n"
    "  \"\\\\begin{align*}\n"
    "     I &= \\\\int x^2 \\\\tan^{-1}(x) \\\\, dx \\\\\n"
    "     \\\\text{IBP: } & u = \\\\tan^{-1}(x), \\\\, dv = x^2 \\\\, dx \\\\\n"
    "                & du = \\\\frac{1}{1+x^2} \\\\, dx, \\\\, v = \\\\frac{x^3}{3} \\\\\n"
    "     I &= \\\\frac{x^3}{3} \\\\tan^{-1}(x) - \\\\int \\\\frac{x^3}{3(1+x^2)} \\\\, dx \\\\\n"
    "       &= \\\\frac{x^3}{3} \\\\tan^{-1}(x) - \\\\frac{1}{3} \\\\int \\\\frac{x^3}{1+x^2} \\\\, dx \\\\\n"
    "     \\\\text{Long Division: } & \\\\frac{x^3}{x^2+1} = x - \\\\frac{x}{x^2+1} \\\\\n"
    "     I &= \\\\frac{x^3}{3} \\\\tan^{-1}(x) - \\\\frac{1}{3} \\\\int \\\\left( x - \\\\frac{x}{x^2+1} \\\\right) \\\\, dx \\\\\n"
    "       &= \\\\frac{x^3}{3} \\\\tan^{-1}(x) - \\\\frac{1}{3} \\\\left[ \\\\frac{x^2}{2} - \\\\frac{1}{2} \\\\ln(1+x^2) \\\\right] + C \\\\\n"
    "       &= \\\\frac{x^3}{3} \\\\tan^{-1}(x) - \\\\frac{x^2}{6} + \\\\frac{1}{6} \\\\ln(1+x^2) + C\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาค่าของ } \\\\int ... dx\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"E3: Reduction Formula": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "E3. Let $S_n = \\int_{0}^{\\pi/3} \\sec^n x \\, dx$. \n"
    "(a) Find $S_1, S_2$. \n"
    "(b) Show that $(n-1)S_n = 2^{n-2}\\sqrt{3} + (n-2)S_{n-2}$.\n"
    "(c) Find $S_3, S_4, S_5$.\n\n"
    "Your task:\n"
    "1) Generate ONE NEW problem that follows the **exact logic of E3(b) and E3(c)**: the user must **derive a reduction formula** using Integration by Parts (IBP), and then **use it** to calculate a value.\n"
    "2) The problem must be 'ถึกขึ้น' (more tedious) by using a **different function**.\n"
    "   - Do NOT use $\\int \\sec^n x dx$ or $\\int \\cos^n x dx$.\n"
    "   - A good candidate is $I_n = \\int (\ln x)^n \\, dx$ or $J_n = \\int x^n e^{ax} \\, dx$.\n"
    "   - Make it a definite integral (e.g., $\\int_1^e (\ln x)^n \\, dx$) to make the evaluation non-trivial.\n"
    "3) The question must ask for two parts: (a) Prove the reduction formula $I_n = f(n, I_{n-1})$ and (b) Use the formula to find a specific value (e.g., $I_3$ or $I_4$).\n"
    "4) Solve it completely, showing the IBP derivation and the recursive calculation.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, IBP, Base Case, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example for $I_n = \\int_1^e (\ln x)^n dx$):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{(a) Let } I_n &= \\\\int_1^e (\ln x)^n \\\\, dx \\\\\n"
    "     \\\\text{IBP: } & u = (\ln x)^n, \\\\, dv = dx \\\\\n"
    "                & du = n(\ln x)^{n-1} \\\\cdot \\\\frac{1}{x} \\\\, dx, \\\\, v = x \\\\\n"
    "     I_n &= \\\\left[ x(\ln x)^n \\\\right]_1^e - \\\\int_1^e x \\\\cdot n(\ln x)^{n-1} \\\\cdot \\\\frac{1}{x} \\\\, dx \\\\\n"
    "     I_n &= (e(\ln e)^n - 1(\ln 1)^n) - n \\\\int_1^e (\ln x)^{n-1} \\\\, dx \\\\\n"
    "     I_n &= (e(1)^n - 1(0)^n) - n I_{n-1} \\\\\n"
    "     I_n &= e - n I_{n-1} \\\\quad (\\\\text{Q.E.D.}) \\\\\n"
    "     \\\\text{(b) Find } I_3: & \\\\\n"
    "     \\\\text{Base Case } I_0 &= \\\\int_1^e (\ln x)^0 \\\\, dx = \\\\int_1^e 1 \\\\, dx = [x]_1^e = e-1 \\\\\n"
    "     I_1 &= e - 1 \cdot I_0 = e - (e-1) = 1 \\\\\n"
    "     I_2 &= e - 2 \cdot I_1 = e - 2(1) = e-2 \\\\\n"
    "     I_3 &= e - 3 \cdot I_2 = e - 3(e-2) = e - 3e + 6 = 6 - 2e\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{กำหนดให้ } I_n = ... \\\\text{ (a) จงแสดงความสัมพันธ์ลดทอน } I_n = ... \\\\text{ (b) จงใช้ผลลัพธ์นี้หาค่า } I_...\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"E4: Area of Intersection": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "E4(c) จงหาพื้นที่ของบริเวณที่อยู่ภายในวงกลม $x^{2}+y^{2}=12$ และวงกลม $(x-3)^{2}+(y-3)^{2}=3(\\sqrt{3}-1)^{2}$\n\n"
    "Your task:\n"
    "1) Generate ONE NEW area problem that follows the **core logic of E4(c): finding the area of a complex intersecting region**.\n"
    "2) The problem must be 'ถึกขึ้น' (significantly more tedious) by using **Polar Coordinates** instead of Cartesian coordinates.\n"
    "   - The region should be defined by two polar curves (e.g., $r = f(\\theta)$ and $r = g(\\theta)$).\n"
    "   - The question should ask for the area of intersection, or the area **inside** one curve but **outside** the other.\n"
    "   - This forces the use of the polar area formula $A = \\frac{1}{2} \\int (r_{outer}^2 - r_{inner}^2) \\, d\\theta$.\n"
    "   - The resulting integral should require non-trivial integration (e.g., using power-reduction for $\\sin^2 \\theta$ or $\\cos^2 \\theta$).\n"
    "3) The AI must solve for the total area completely, showing intersection points and the full integral setup.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Area, Inside, Outside, Intersections, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Find area inside } r=3\\\\cos\\\\theta & \\\\text{ and outside } r=1+\\\\cos\\\\theta. \\\\\n"
    "     \\\\text{Intersections: } & 3\\\\cos\\\\theta = 1+\\\\\cos\\\\theta \\\\Rightarrow 2\\\\cos\\\\theta = 1 \\\\\n"
    "     & \\\\cos\\\\theta = 1/2 \\\\Rightarrow \\\\theta = -\\\\pi/3, \\\\pi/3. \\\\\n"
    "     \\\\text{Area } A &= \\\\frac{1}{2} \\\\int_{-\\\\pi/3}^{\\\\pi/3} (r_{outer}^2 - r_{inner}^2) \\\\, d\\\\theta \\\\\n"
    "     A &= \\\\frac{1}{2} \\\\int_{-\\\\pi/3}^{\\\\pi/3} ( (3\\\\cos\\\\theta)^2 - (1+\\\\\cos\\\\theta)^2 ) \\\\, d\\\\theta \\\\\n"
    "     A &= \\\\frac{1}{2} \\\\int_{-\\\\pi/3}^{\\\\pi/3} ( 9\\\\cos^2\\\\theta - (1 + 2\\\\cos\\\\theta + \\\\cos^2\\\\theta) ) \\\\, d\\\\theta \\\\\n"
    "     A &= \\\\frac{1}{2} \\\\int_{-\\\\pi/3}^{\\\\pi/3} ( 8\\\\cos^2\\\\theta - 2\\\\cos\\\\theta - 1 ) \\\\, d\\\\theta \\\\\n"
    "     \\\\text{Use } \\\\cos^2\\\\theta &= \\\\frac{1+\\\\\cos(2\\\\theta)}{2} \\\\\n"
    "     A &= \\\\frac{1}{2} \\\\int_{-\\\\pi/3}^{\\\\pi/3} ( 8(\\\\frac{1+\\\\\cos(2\\\\theta)}{2}) - 2\\\\cos\\\\theta - 1 ) \\\\, d\\\\theta \\\\\n"
    "     A &= \\\\frac{1}{2} \\\\int_{-\\\\pi/3}^{\\\\pi/3} ( 4 + 4\\\\cos(2\\\\theta) - 2\\\\cos\\\\theta - 1 ) \\\\, d\\\\theta \\\\\n"
    "     A &= \\\\frac{1}{2} \\\\int_{-\\\\pi/3}^{\\\\pi/3} ( 3 + 4\\\\cos(2\\\\theta) - 2\\\\cos\\\\theta ) \\\\, d\\\\theta \\\\\n"
    "     A &= \\\\frac{1}{2} \\\\left[ 3\\\\theta + 2\\\\sin(2\\\\theta) - 2\\\\sin\\\\theta \\\\right]_{-\\\\pi/3}^{\\\\pi/3} \\\\\n"
    "     \\\\text{(By symmetry)} &= \\\\left[ 3\\\\theta + 2\\\\sin(2\\\\theta) - 2\\\\sin\\\\theta \\\\right]_{0}^{\\\\pi/3} \\\\\n"
    "     &= (3(\\\\pi/3) + 2\\\\sin(2\\\\pi/3) - 2\\\\sin(\\\\pi/3)) - (0) \\\\\n"
    "     &= \\\\pi + 2(\\\\frac{\\\\sqrt{3}}{2}) - 2(\\\\frac{\\\\sqrt{3}}{2}) = \\\\pi\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาพื้นที่ของบริเวณที่ (ในพิกัดเชิงขั้ว) ... (เช่น อยู่ภายใน } r=... \\\\text{ และอยู่ภายนอก } r=...)\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"F1: Partial Fractions": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "F1(a) $\\int \\frac{2x-1}{(x+1)^2} dx$ (Repeated Linear)\n"
    "F1(b) $\\int \\frac{2x^2+5x-6}{x^2-x-2} dx$ (Improper, requires Long Division)\n"
    "F1(c) $\\int \\frac{4x^2+12}{x^3+4x} dx$ (Irreducible Quadratic)\n\n"
    "Your task:\n"
    "1) Generate ONE NEW integral problem that is 'ถึกขึ้น' (more tedious) by **combining all complex logic from F1**.\n"
    "2) The integral $\\int \\frac{P(x)}{Q(x)} dx$ MUST be **improper** (Degree P $\\ge$ Degree Q), requiring **Polynomial Long Division** first (like F1b).\n"
    "3) The denominator of the remaining proper fraction, $Q(x)$, must be complex. It MUST contain **BOTH**:\n"
    "   - at least one **repeated linear factor** (like F1a, e.g., $(x-1)^2$)\n"
    "   - at least one **irreducible quadratic factor** (like F1c, e.g., $(x^2+4)$)\n"
    "   - Example $Q(x) = (x-1)^2(x^2+4)$.\n"
    "4) The AI must solve the integral completely, showing the long division, the full partial fraction decomposition (e.g., $\\frac{A}{x-1} + \\frac{B}{(x-1)^2} + \\frac{Cx+D}{x^2+4}$), solving for all coefficients (A, B, C, D), and integrating all resulting terms.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Long Division, Setup, Solve for A/B/C, Integrate, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example for setup only):\n"
    "  \"\\\\begin{align*}\n"
    "     \\\\text{Long Division:} & \\\\frac{x^5}{(x-1)^2(x^2+1)} = (x+2) + \\\\frac{3x^3-x^2+3x-2}{(x-1)^2(x^2+1)} \\\\\n"
    "     \\\\text{Setup:} & \\\\frac{...}{(x-1)^2(x^2+1)} = \\\\frac{A}{x-1} + \\\\frac{B}{(x-1)^2} + \\\\frac{Cx+D}{x^2+1} \\\\\n"
    "     \\\\text{Solving for A, B, C, D...} & \\\\\n"
    "     A = ... & B = ... & C = ... & D = ... \\\\\n"
    "     \\\\text{Integrate:} & \\\\int (x+2) dx + \\\\int \\\\frac{A}{x-1} dx + \\\\int \\\\frac{B}{(x-1)^2} dx + \\\\int \\\\frac{Cx+D}{x^2+1} dx \\\\\n"
    "     ... &= \\\\frac{x^2}{2} + 2x + A \\\\ln|x-1| - \\\\frac{B}{x-1} + \\\\frac{C}{2}\\\\ln(x^2+1) + D \\\\tan^{-1}(x) + C_{final}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาค่าของ } \\\\int ... dx\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"F2: Improper Integrals": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "F2. จงพิจารณาว่าอินทิกรัลไม่ตรงแบบต่อไปนี้ลู่เข้าหรือลู่ออก ถ้าลู่เข้า จงหาค่า\n"
    "F2(b) $\\int_{-\\infty}^{\\infty}\\frac{1}{(2x-5)^{6}}dx$ (Type 1, must split at $c$)\n"
    "F2(d) $\\int_{-1}^{\\infty}\\frac{1}{\\sqrt[3]{x+1}}dx$ (Mixed Type, discontinuity at -1 and infinite bound)\n\n"
    "Your task:\n"
    "1) Generate ONE NEW improper integral problem that follows the **most complex logic from F2**: it MUST require **splitting into two separate integrals** (and two limits) to solve.\n"
    "   - This means either a Type 1 integral from $\\int_{-\\infty}^{\\infty}$ (like F2b) OR a Mixed Type integral $\\int_a^\\infty$ with a discontinuity at $x=a$ (like F2d).\n"
    "2) The problem must be 'ถึกขึ้น' (more tedious) by making the integrand non-trivial, e.g., requiring a **u-substitution** (like $x e^{-x^2}$) or simple **Integration by Parts** to solve the antiderivative before evaluating the limits.\n"
    "3) The AI must solve it completely: show the split into two limits, find the antiderivative, evaluate both limits, and conclude convergence or divergence.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Split, Limit 1, Limit 2, Converges, Diverges, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example for $\\int_{-\\infty}^{\\infty} x e^{-x^2} dx$):\n"
    "  \"\\\\begin{align*}\n"
    "     I &= \\\\int_{-\\infty}^{\\infty} x e^{-x^2} dx \\\\\n"
    "     \\\\text{Split at } x=0: & I = \\\\int_{-\\infty}^{0} x e^{-x^2} dx + \\\\int_{0}^{\\infty} x e^{-x^2} dx \\\\\n"
    "     I &= \\\\lim_{a \\to -\\infty} \\\\int_{a}^{0} x e^{-x^2} dx + \\\\lim_{b \\to \\infty} \\\\int_{0}^{b} x e^{-x^2} dx \\\\\n"
    "     \\\\text{Antiderivative: } & \\\\text{Let } u = -x^2, \\\\, du = -2x dx \\\\Rightarrow x dx = -\\frac{1}{2} du \\\\\n"
    "     & \\\\int x e^{-x^2} dx = \\\\int e^u (-\\frac{1}{2} du) = -\\frac{1}{2} e^u = -\\frac{1}{2} e^{-x^2} \\\\\n"
    "     \\\\text{Limit 1: } & \\\\lim_{a \\to -\\infty} \\\\left[ -\\frac{1}{2} e^{-x^2} \\\\right]_{a}^{0} = \\\\lim_{a \\to -\\infty} ( -\\frac{1}{2} e^{0} - (-\\frac{1}{2} e^{-a^2}) ) \\\\\n"
    "     & = -\\frac{1}{2} - \\\\lim_{a \\to -\\infty} (-\\frac{1}{2e^{a^2}}) = -\\frac{1}{2} - 0 = -\\frac{1}{2} \\\\\n"
    "     \\\\text{Limit 2: } & \\\\lim_{b \\to \\infty} \\\\left[ -\\frac{1}{2} e^{-x^2} \\\\right]_{0}^{b} = \\\\lim_{b \\to \\infty} ( -\\frac{1}{2} e^{-b^2} - (-\\frac{1}{2} e^{0}) ) \\\\\n"
    "     & = \\\\lim_{b \\to \\infty} (-\\frac{1}{2e^{b^2}}) + \\frac{1}{2} = 0 + \\frac{1}{2} = \\frac{1}{2} \\\\\n"
    "     \\\\text{Total: } & I = (-\\frac{1}{2}) + (\\frac{1}{2}) = 0. \\\\text{ (Converges)}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงพิจารณาว่าอินทิกรัลไม่ตรงแบบ ... ลู่เข้าหรือลู่ออก ถ้าลู่เข้า จงหาค่า}\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
"}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
),"F3: Arc Length": (
    "You are an AI Question Generator for a Calculus I final review.\n"
    "Original exam model:\n"
    "F3. จงหาความยาวส่วนโค้งของ $y=\\frac{4e^{2x}+1}{4e^{x}}$ (which is $y = e^x + \\frac{1}{4}e^{-x}$) จาก $x=0$ ถึง $x=1$.\n"
    "   - The core logic is that $1 + (y')^2$ simplifies to a perfect square: $1 + (e^x - \\frac{1}{4}e^{-x})^2 = (e^x + \\frac{1}{4}e^{-x})^2$.\n\n"
    "Your task:\n"
    "1) Generate ONE NEW arc length problem that follows the **exact same logic**.\n"
    "2) The problem must be 'ถึกขึ้น' (more tedious) by using a **non-exponential function**, such as a polynomial $f(x) = ax^n + bx^{-m}$.\n"
    "   - You must choose the constants $a, b, n, m$ such that $1 + (f'(x))^2$ simplifies to a new perfect square.\n"
    "   - This is the key 'trick' of arc length problems.\n"
    "   - Example function: $f(x) = \\frac{x^3}{6} + \\frac{1}{2x}$. (Here $f' = \\frac{x^2}{2} - \\frac{1}{2x^2}$, so $1+(f')^2 = (\\frac{x^2}{2} + \\frac{1}{2x^2})^2$)\n"
    "3) The AI must solve it completely, showing the derivative $f'(x)$, the algebra for $1 + (f'(x))^2$, finding the perfect square, taking the square root, and integrating.\n\n"
    "VERY IMPORTANT LaTeX RULES:\n"
    "- The value of `solution_latex` MUST be a **single math environment** starting with\n"
    "  `\\\\begin{align*}` and ending with `\\\\end{align*}`.\n"
    "- If you need to write words (Let, Derivative, Simplify, Arc Length, etc.), wrap them inside `\\\\text{...}`.\n"
    "- Example of the STYLE (example only):\n"
    "  \"\\\\begin{align*}\n"
    "     y &= \\\\frac{x^3}{6} + \\\\frac{1}{2x} \\\\text{, from } x=1 \\\\text{ to } x=2. \\\\\n"
    "     y' &= \\\\frac{3x^2}{6} - \\\\frac{1}{2x^2} = \\\\frac{x^2}{2} - \\\\frac{1}{2x^2} \\\\\n"
    "     (y')^2 &= \\\\left( \\\\frac{x^2}{2} - \\\\frac{1}{2x^2} \\\\right)^2 = \\\\frac{x^4}{4} - 2(\\\\frac{x^2}{2})(\\\\frac{1}{2x^2}) + \\\\frac{1}{4x^4} \\\\\n"
    "     (y')^2 &= \\\\frac{x^4}{4} - \\\\frac{1}{2} + \\\\frac{1}{4x^4} \\\\\n"
    "     1 + (y')^2 &= 1 + \\\\frac{x^4}{4} - \\\\frac{1}{2} + \\\\frac{1}{4x^4} \\\\\n"
    "     1 + (y')^2 &= \\\\frac{x^4}{4} + \\\\frac{1}{2} + \\\\frac{1}{4x^4} = \\\\left( \\\\frac{x^2}{2} + \\\\frac{1}{2x^2} \\\\right)^2 \\\\\n"
    "     \\\\sqrt{1 + (y')^2} &= \\\\frac{x^2}{2} + \\\\frac{1}{2x^2} \\\\\n"
    "     L &= \\\\int_1^2 \\\\left( \\\\frac{x^2}{2} + \\\\frac{1}{2}x^{-2} \\\\right) \\\\, dx \\\\\n"
    "     L &= \\\\left[ \\\\frac{x^3}{6} - \\\\frac{1}{2x} \\\\right]_1^2 \\\\\n"
    "     L &= \\\\left( \\\\frac{8}{6} - \\\\frac{1}{4} \\\\right) - \\\\left( \\\\frac{1}{6} - \\\\frac{1}{2} \\\\right) \\\\\n"
    "       &= \\\\left( \\\\frac{4}{3} - \\\\frac{1}{4} \\\\right) - \\\\left( \\\\frac{1}{6} - \\\\frac{3}{6} \\\\right) = \\\\frac{13}{12} - (-\\frac{2}{6}) = \\\\frac{13}{12} + \\\\frac{1}{3} = \\\\frac{17}{12}\n"
    "   \\\\end{align*}\".\n\n"
    "Output format:\n"
    "{\n"
    "  \"question_latex\": \"\\\\text{จงหาความยาวของเส้นโค้ง } y = ... \\\\text{ จาก } x=a \\\\text{ ถึง } x=b\",\n"
    "  \"solution_latex\": \"\\\\begin{align*} ... \\\\end{align*}\"\n"
    "}\n"
    "Return ONLY this JSON object. No extra keys, no explanations outside LaTeX."
)
}

st.set_page_config(layout="wide")
st.title("🧠 Quiz – Calculus I (Final Review)")

st.write("เลือกประเภทโจทย์ตาม Flie Final Review Problems")

problem_type = st.selectbox("เลือกแนวโจทย์:", PROMPT_TEMPLATES.keys())

if st.button("🚀 Gen Problem"):
    selected_prompt = PROMPT_TEMPLATES[problem_type]

    with st.spinner("กำลังให้ AI สร้างโจทย์..."):
        try:
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=selected_prompt,
                config=generation_config,
            )
            data = json.loads(response.text)
            st.session_state.current_problem = {
                "type": problem_type,
                "question_latex": data.get("question_latex", ""),
                "solution_latex": data.get("solution_latex", ""),
            }
        except Exception as e:
            st.error(f"AI ส่งข้อมูลกลับมาผิดพลาด (หรือไม่ใช่ JSON): {e}")
            if 'response' in locals():
                st.error(f"ข้อมูลดิบที่ได้รับจากโมเดล: {response.text}")

if "current_problem" in st.session_state:
    prob = st.session_state.current_problem

    st.subheader(f"แนวที่เลือก: {prob['type']}")

    st.markdown("### 📘 โจทย์")
    if prob["question_latex"]:
        st.latex(prob["question_latex"])
        with st.expander("ดูโค้ด LaTeX ของโจทย์ (ก๊อปไปใช้ต่อได้)"):
            st.code(prob["question_latex"], language="latex")
    else:
        st.warning("ไม่มี `question_latex` ใน JSON ที่ได้รับ")

    st.markdown("### ✅ เฉลย")
    if prob["solution_latex"]:
        st.latex(prob["solution_latex"])
        with st.expander("ดูโค้ด LaTeX ของเฉลย (ก๊อปไปใช้ต่อได้)"):
            st.code(prob["solution_latex"], language="latex")
    else:
        st.warning("ไม่มี `solution_latex` ใน JSON ที่ได้รับ")
